### ISSUE TITLE
Failed to fetch profile. Please try again later.

### ISSUE THREAD

**Issue by bstone-dev** [jcari-dev/chess-react#49]

**Comment by jcari-dev** [comment]
What is your user_id?

**Comment by jcari-dev** [comment]
Whoops mb!

The reason is because this code is actually looking at localhost, I need to put the correct URL to an env.

Fixing it! thanks tho!

https://github.com/jcari-dev/chess-react/blob/46c5d65a238cc79bb123bc296a5762815e95c0eb/chess/src/pages/profile/Profile.js#L27-L29

**Comment by jcari-dev** [comment]
It should be up and running :)

**Comment by jcari-dev** [comment]
![image](https://github.com/jcari-dev/chess-react/assets/65676916/a8e8271c-fd2a-49ca-a3ba-f8948462b69c)
